# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: step-functions-express
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

useDotenv: true

# Deprecations
#variablesResolutionMode: 20210326

provider:
  name: aws
  runtime: nodejs12.x

# you can overwrite defaults here
  stage: ${env:STAGE}
  region: ${env:REGION}
  stackName: step-functions-express
  apiName: step-functions-express-${sls:stage} # Use a custom name for the API Gateway API
  memorySize: 128
  timeout: 10
  logRetentionInDays: 1
  deploymentBucket:
    name: moscloud.sls.${self:provider.region}.deploys
    tags: # Tags that will be added to each of the deployment resources
      environment: dev
      project: ${self:custom.projectName}
  deploymentPrefix: serverless # The S3 prefix under which deployed artifacts should be stored. Default is serverless
  lambdaHashingVersion: 20201221
  versionFunctions: true
  stackTags: # Optional CF stack tags
    stage: ${sls:stage}
    project: ${self:custom.projectName}
  
#  apiGateway:
#    description: API REST for step-functions-express ${sls:stage}
#    # apiKeySourceType: HEADER # Source of API key for usage plan. HEADER or AUTHORIZER.
#    apiKeys: # List of API keys to be used by your service API Gateway REST API
#      - name: step-functions-express-api-key-${sls:stage}
#        value: ${env:API_KEY}
#        description: API key for step-functions-express ${sls:stage}
#      #  customerId: myFirstKeyCustomerId
#    usagePlan: # Optional usage plan configuration
#      quota:
#        limit: 100
#      #  offset: 2
#        period: DAY
#      throttle:
#        burstLimit: 20
#        rateLimit: 10

# you can add statements to the Lambda function's IAM Role here
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "s3:GetObject"
          Resource: arn:aws:s3:::${self:custom.moviesJsonBucket}/*
        - Effect: "Allow"
          Action:
            - "s3:PutObject"
            - "s3:PutObjectTagging"
          Resource:
            - arn:aws:s3:::${self:custom.posterMoviesBucket}/*
        - Effect: "Allow"
          Action:
            - "sqs:SendMessage"
          Resource:
            Fn::GetAtt: [QueueSQS, Arn]
        - Effect: "Allow"
          Action:
            - states:StartExecution
            - states:StartSyncExecution
          Resource: "arn:aws:states:${self:provider.region}:${aws:accountId}:stateMachine:MovieProcessor${self:provider.stage}"
      tags:
        project: ${self:custom.projectName}
#        Fn::Join:
#          - ""
#          - - "arn:aws:s3:::"
#            - "Ref" : "ServerlessDeploymentBucket"
#            - "/*"

# you can define service wide environment variables here
#  environment:
#    variable1: value1

custom:
  functionsBasePath: src/handlers
  prune:
    automatic: true
    number: 3
  moviesJsonBucket: movies-file-${sls:stage}
  posterMoviesBucket: movies-posters-${sls:stage}
  projectName: step-functions-express
  prefixProject: sfe

# you can add packaging information here
package:
  individually: true
  excludeDevDependencies: true
  patterns:
    - "!local/**"
    - "!.vscode/**"
    - "!node_modules/**/**.md"
    - "!node_modules/**/test/**"
    - "!node_modules/**/LICENSE"
    - "!node_modules/**/LICENCE"
    - "!node_modules/**/License"
    - "!node_modules/**/license"
    - "!node_modules/**/Makefile"
    - "!node_modules/**/**.ts"
    - "!node_modules/**/package-lock.json"
    - "!node_modules/**/aws-sdk/**"
    - "!./yarn.*"
    - "!./**.md"
    - "!./package.json"
    - "!./package-lock.json"
    - "!.git/**"
    - "!.travis.yml"

plugins:
  - serverless-dotenv-plugin
  - serverless-prune-plugin
  - serverless-plugin-include-dependencies
  - serverless-functions-base-path
  - serverless-step-functions

functions:
  hello:
      handler: handler.hello
      name: ${self:custom.prefixProject}-hello-${sls:stage}
      timeout: 15
      reservedConcurrency: 5
      events:
        - http:
            path: hello
            method: get
  readFile:
    handler: readFile.index
    name: ${self:custom.prefixProject}-readFile-${sls:stage}
    timeout: 240
    memorySize: 512
    description: Triggered function to read files from bucket ${self:custom.moviesJsonBucket}
    events:
      - s3:
          bucket:
            Ref: MoviesFilesBucket
          event: s3:ObjectCreated:*
          rules:
            - suffix: .json
          existing: true
    environment:
      SQS_ARN:
        Fn::GetAtt: [QueueSQS, Arn]
      SQS_URL: { Ref: QueueSQS }
  sqsConsumer:
    handler: sqsConsumer.index
    name: ${self:custom.prefixProject}-sqsConsumer-${sls:stage}
    memorySize: 512
    description: Function to receive data from SQS and get poster images.
    reservedConcurrency: 10
    events:
      - sqs:
          arn:
            Fn::GetAtt: [QueueSQS, Arn]
          batchSize: 20
          maximumBatchingWindow: 5 # Seconds to wait for a batch
    environment:
      SQS_ARN:
        Fn::GetAtt: [QueueSQS, Arn]
      SQS_URL: { Ref: QueueSQS }
      POSTER_BUCKET_NAME: ${self:custom.posterMoviesBucket}
      STATE_MACHINE_ARN: ${self:resources.Outputs.MoviesStepMachineARN.Value}
  # Step Functions FLow
  getImagePosterToS3:
    handler: steps/getImagePosterToS3.index
    name: ${self:custom.prefixProject}-getImagePosterToS3-${sls:stage}
    description: Function to receive data from SQS and save poster images.
    #reservedConcurrency: 10
    environment:
      SQS_ARN:
        Fn::GetAtt: [QueueSQS, Arn]
      SQS_URL: { Ref: QueueSQS }
      POSTER_BUCKET_NAME: ${self:custom.posterMoviesBucket}
  registerMovieDB:
    handler: steps/registerMovieDB.index
    name: ${self:custom.prefixProject}-registerMovieDB-${sls:stage}
    description: Save info to database.
    #reservedConcurrency: 10
  #   environment:
  #     SQS_ARN:
  #       Fn::GetAtt: [QueueSQS, Arn]
  posterImageException:
    handler: steps/exceptions/posterImageException.index
    name: ${self:custom.prefixProject}-posterImageException-${sls:stage}
    description: Process error when trying to get poster images.
    reservedConcurrency: 1

stepFunctions:
  stateMachines:
    MovieProcessor:
      type: EXPRESS
      useExactVersion: true
      loggingConfig:
        level: ALL
        includeExecutionData: true
        destinations:
          - Fn::GetAtt:
              - MovieProcessorLogGroup
              - Arn
      name: MovieProcessor${self:provider.stage}
      definition:
        Comment: State Machine for processing all movies info.
        StartAt: GetImagePosterToS3
        States:
          GetImagePosterToS3:
            Type: Map
            InputPath: "$"
            ItemsPath: "$.imageSizes"
            MaxConcurrency: 7
            Comment: Get all original poster image.
            Parameters:
              size.$: "$$.Map.Item.Value"
              movie.$: "$.movie"
            Iterator:
              StartAt: GetImage
              States:
                GetImage:
                  Type: Task
                  Resource:
                    Fn::GetAtt: [getImagePosterToS3, Arn]
                  End: true
            ResultPath: "$"
            Catch:
              - ErrorEquals:
                  - "States.ALL"
                Next: MovieProcessException
            Next: SetMovieDB
            #End: true
          SetMovieDB:
            Type: Task
            Resource:
              Fn::GetAtt: [registerMovieDB, Arn]
            Comment: Save info to database.
            ResultPath: "$"
            Catch:
              - ErrorEquals:
                  - "States.ALL"
                Next: MovieProcessException
            End: true
          MovieProcessException:
            Type: Task
            Resource:
              Fn::GetAtt: [posterImageException, Arn]
            Comment: Manage error in movie process.
            End: true

# you can add CloudFormation resource templates here
resources:
  Resources:
    MoviesFilesBucket:
      Type: AWS::S3::Bucket
      Properties: 
        BucketName: ${self:custom.moviesJsonBucket}
        VersioningConfiguration:
          Status: Suspended
        PublicAccessBlockConfiguration:
          BlockPublicAcls: true
          BlockPublicPolicy: true
          IgnorePublicAcls: true
          RestrictPublicBuckets: true
        Tags:
          - Key: project
            Value: ${self:provider.stackName}
          - Key: environment
            Value: ${sls:stage}
    PosterMoviesBucket:
      Type: AWS::S3::Bucket
      Properties: 
        BucketName: ${self:custom.posterMoviesBucket}
        #VersioningConfiguration:
        #  Status: Suspended
        PublicAccessBlockConfiguration:
          BlockPublicAcls: true
          BlockPublicPolicy: true
          IgnorePublicAcls: true
          RestrictPublicBuckets: true
        Tags:
          - Key: project
            Value: ${self:provider.stackName}
          - Key: environment
            Value: ${sls:stage}
    QueueSQS:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:custom.prefixProject}-queue-${sls:stage}
        #DelaySeconds: 5
        #MessageRetentionPeriod: 600 #seconds
        #ReceiveMessageWaitTimeSeconds: 5
        #RedrivePolicy:
          #deadLetterTargetArn: arn
          #maxReceiveCount: 2
        VisibilityTimeout: 15 #seconds
        Tags:
          - Key: project
            Value: ${self:provider.stackName}
          - Key: environment
            Value: ${sls:stage}
    MovieProcessorLogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        RetentionInDays: 1
        LogGroupName: sfe-movieProcessorLogGroup-${sls:stage}
#    CognitoUserPool:
#      Type: AWS::Cognito::UserPool
#      Properties:
#        UserPoolName: sls-user-pool-${sls:stage}
#        UsernameAttributes: 
#          - email
#        AutoVerifiedAttributes:
#          - email
#    CognitoUserPoolClient:
#      Type: AWS::Cognito::UserPoolClient
#      Properties:
#          ClientName: sls-user-pool-client-${sls:stage}
#          UserPoolId:
#            Ref: CognitoUserPool
#          ExplicitAuthFlows:
#            - ADMIN_NO_SRP_AUTH
#          GenerateSecret: false
#          PreventUserExistenceErrors: LEGACY
  Outputs:
    MoviesStepMachineARN:
      Description: ARN for Step Function for movies-processor-machine-${self:provider.stage}
      Value:
        Ref: MovieProcessor${self:provider.stage}
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
